name: javier
channels:
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas
  - python-dotenv
  - requests
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - krakenex
      - schedule
      - tensorflow
      - web3>=7,<8
